apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv-01
spec: 
  capacity:
    storage: 1Gi
  accessModes: 
  - ReadWriteOnce
  hostPath: 
    path: /tmp/pv-01

---

apiVersion: v1
kind: PersistentVolume 
metadata: 
  name: pv-02
spec: 
  capacity: 
    storage: 1Gi
  accessModes: 
  - ReadWriteOnce 
  hostPath: 
    path: /tmp/pv-02   
